/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

/**
 *
 * @author mallo
 */
public class AddDelete extends javax.swing.JFrame {

    /**
     * Creates new form AddDelete
     */
    public AddDelete() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("AddDelete");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jFREF = new javax.swing.JTextField();
        jFNAME = new javax.swing.JTextField();
        jFPRE = new javax.swing.JTextField();
        jFCAD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JBAÑADIR = new javax.swing.JButton();
        JBBORRAR = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(450, 700));
        jPanel1.setLayout(null);

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(340, 30, 62, 32);

        jFREF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFREFActionPerformed(evt);
            }
        });
        jPanel1.add(jFREF);
        jFREF.setBounds(80, 240, 280, 30);
        jPanel1.add(jFNAME);
        jFNAME.setBounds(80, 300, 280, 30);
        jPanel1.add(jFPRE);
        jFPRE.setBounds(80, 360, 280, 30);
        jPanel1.add(jFCAD);
        jFCAD.setBounds(80, 420, 280, 30);

        jLabel2.setText("FECHA CADUCIDAD");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 400, 270, 16);

        jLabel3.setText("NÚMERO DE REFERENCIA");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 220, 270, 16);

        jLabel4.setText("NOMBRE PRODUCTO");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 280, 270, 16);

        jLabel5.setText("PRECIO");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 340, 270, 16);

        JBAÑADIR.setText("AÑADIR");
        JBAÑADIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAÑADIRActionPerformed(evt);
            }
        });
        jPanel1.add(JBAÑADIR);
        JBAÑADIR.setBounds(80, 490, 290, 40);

        JBBORRAR.setText("BORRAR");
        JBBORRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBORRARActionPerformed(evt);
            }
        });
        jPanel1.add(JBBORRAR);
        JBBORRAR.setBounds(80, 540, 290, 40);
        jPanel1.add(Fondo);
        Fondo.setBounds(-9, -4, 470, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Principal obj = new Principal();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jFREFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFREFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFREFActionPerformed

    private void JBAÑADIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAÑADIRActionPerformed
        // TODO add your handling code here:
        String [] Datos =  new String [4];
        Datos[0]=jFREF.getText();
        jFREF.setText(null);
        Datos[1]=jFNAME.getText();
        jFNAME.setText(null);
        Datos[2]=jFPRE.getText();
        jFPRE.setText(null);
        Datos[3]=jFCAD.getText();
        jFCAD.setText(null);
    }//GEN-LAST:event_JBAÑADIRActionPerformed

    private void JBBORRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBORRARActionPerformed
        // TODO add your handling code here:
        jFREF.setText(null);
        jFNAME.setText(null);
        jFPRE.setText(null);
        jFCAD.setText(null);
    }//GEN-LAST:event_JBBORRARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton JBAÑADIR;
    private javax.swing.JButton JBBORRAR;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jFCAD;
    private javax.swing.JTextField jFNAME;
    private javax.swing.JTextField jFPRE;
    private javax.swing.JTextField jFREF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
