/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mallo
 */
public class Visualizar extends javax.swing.JFrame {

    DefaultTableModel modelotablaComida = new DefaultTableModel();

    public Visualizar() {

        initComponents();
        inicializarModeloTabla();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Visualizar");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaComida = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jBAdd = new javax.swing.JButton();
        jBDelete = new javax.swing.JButton();
        jTRef = new javax.swing.JTextField();
        jTPrecio = new javax.swing.JTextField();
        jTName = new javax.swing.JTextField();
        jTCaducidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        borrarTodo = new javax.swing.JButton();
        BORRARPRODUCTO = new javax.swing.JButton();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(450, 700));
        jPanel1.setLayout(null);

        tablaComida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaComida);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 410, 340);

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(340, 20, 62, 32);

        jBAdd.setText("AÑADIR");
        jBAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddActionPerformed(evt);
            }
        });
        jPanel1.add(jBAdd);
        jBAdd.setBounds(40, 620, 180, 32);

        jBDelete.setText("RESETEAR ENTRADAS");
        jBDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jBDelete);
        jBDelete.setBounds(220, 620, 180, 32);

        jTRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTRefActionPerformed(evt);
            }
        });
        jPanel1.add(jTRef);
        jTRef.setBounds(20, 460, 180, 40);
        jPanel1.add(jTPrecio);
        jTPrecio.setBounds(20, 530, 180, 40);
        jPanel1.add(jTName);
        jTName.setBounds(240, 460, 180, 40);
        jPanel1.add(jTCaducidad);
        jTCaducidad.setBounds(240, 530, 180, 40);

        jLabel1.setText("Numero de Referencia");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 440, 150, 16);

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 440, 150, 16);

        jLabel3.setText("Precio");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 510, 150, 16);

        jLabel4.setText("Caducidad");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(250, 510, 150, 16);

        borrarTodo.setText("ELIMINAR TODO");
        borrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarTodoActionPerformed(evt);
            }
        });
        jPanel1.add(borrarTodo);
        borrarTodo.setBounds(220, 650, 180, 32);

        BORRARPRODUCTO.setText("ELIMINAR PRODUCTO");
        BORRARPRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BORRARPRODUCTOActionPerformed(evt);
            }
        });
        jPanel1.add(BORRARPRODUCTO);
        BORRARPRODUCTO.setBounds(40, 650, 180, 32);
        jPanel1.add(FONDO);
        FONDO.setBounds(0, 0, 450, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Principal obj = new Principal();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTRefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTRefActionPerformed

    private void jBDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteActionPerformed
        // TODO add your handling code here:
        jTRef.setText(null);
        jTName.setText(null);
        jTPrecio.setText(null);
        jTCaducidad.setText(null);
    }//GEN-LAST:event_jBDeleteActionPerformed

    private void jBAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddActionPerformed
        // TODO add your handling code here:
        String[] Datos = new String[4];
        Datos[0] = jTRef.getText();
        jTRef.setText(null);
        Datos[1] = jTName.getText();
        jTName.setText(null);
        Datos[2] = jTPrecio.getText();
        jTPrecio.setText(null);
        Datos[3] = jTCaducidad.getText();
        jTCaducidad.setText(null);
        modelotablaComida.addRow(Datos);
    }//GEN-LAST:event_jBAddActionPerformed

    private void borrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarTodoActionPerformed
        // TODO add your handling code here:

        int cantidadProductos = tablaComida.getRowCount();
        for (int i = 0; i <= cantidadProductos; i++) {
            modelotablaComida.removeRow(i);
        }
        JOptionPane.showMessageDialog(null, "La tabla a sido borrada.");

    }//GEN-LAST:event_borrarTodoActionPerformed

    private void BORRARPRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BORRARPRODUCTOActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaComida.getSelectedRow();
        if (filaSeleccionada >= 0) {
            modelotablaComida.removeRow(filaSeleccionada);
        } else {
            JOptionPane.showMessageDialog(null, "Tabla VACIA o no seleccionó ninguna fila.");
        }
    }//GEN-LAST:event_BORRARPRODUCTOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BORRARPRODUCTO;
    private javax.swing.JLabel FONDO;
    private javax.swing.JButton borrarTodo;
    private javax.swing.JButton jBAdd;
    private javax.swing.JButton jBDelete;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCaducidad;
    private javax.swing.JTextField jTName;
    private javax.swing.JTextField jTPrecio;
    private javax.swing.JTextField jTRef;
    private javax.swing.JTable tablaComida;
    // End of variables declaration//GEN-END:variables

    private void inicializarModeloTabla() {
        modelotablaComida.addColumn("REF");
        modelotablaComida.addColumn("Nombre");
        modelotablaComida.addColumn("Precio");
        modelotablaComida.addColumn("Caducidad");
        this.tablaComida.setModel(modelotablaComida);
    }

}
